### PR TITLE
[FIX] avatar

### LINKED ISSUE #73: Fix avatar with facebook and google

### PR DESCRIPTION
**Pull request by edman193**
closes #73 
Use image with google and facebook

### CODE REVIEW

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -10,6 +11,13 @@ def after_sign_in_path_for(resource)
     end
   end
 
+  def get_user_avatar
```
Comment (jclopezdev) [inline app/controllers/application_controller.rb]: I think that you forgot to add `?type=large'` in facebook image
